global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: training

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: linux-hosts
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml
        refresh_interval: 30s

  - job_name: sample-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - sample-app:8000
        labels:
          application: sample-app
