apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-lab
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/REPLACE_ME/gitops-lab.git
  ref:
    branch: main
  timeout: 60s
