BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER salary_audit_trg';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE employee_api';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE salary_audit CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE departments CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE departments (
  department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  department_name VARCHAR2(100) NOT NULL,
  location_name   VARCHAR2(100),
  CONSTRAINT pk_departments PRIMARY KEY (department_id),
  CONSTRAINT uq_departments_name UNIQUE (department_name)
);

CREATE TABLE employees (
  employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  full_name     VARCHAR2(100) NOT NULL,
  email         VARCHAR2(200) NOT NULL,
  department_id NUMBER NOT NULL,
  manager_id    NUMBER,
  salary        NUMBER(12,2) NOT NULL,
  hire_date     DATE DEFAULT SYSDATE NOT NULL,
  active_flag   CHAR(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT pk_employees PRIMARY KEY (employee_id),
  CONSTRAINT uq_employees_email UNIQUE (email),
  CONSTRAINT ck_employees_salary CHECK (salary >= 0),
  CONSTRAINT ck_employees_active CHECK (active_flag IN ('Y', 'N')),
  CONSTRAINT fk_employees_department FOREIGN KEY (department_id)
    REFERENCES departments (department_id),
  CONSTRAINT fk_employees_manager FOREIGN KEY (manager_id)
    REFERENCES employees (employee_id)
);

CREATE TABLE salary_audit (
  audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  employee_id    NUMBER NOT NULL,
  old_salary     NUMBER(12,2) NOT NULL,
  new_salary     NUMBER(12,2) NOT NULL,
  changed_by     VARCHAR2(128) NOT NULL,
  changed_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_salary_audit PRIMARY KEY (audit_id),
  CONSTRAINT fk_salary_audit_employee FOREIGN KEY (employee_id)
    REFERENCES employees (employee_id)
);
